version: '3.4'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.2.0
    container_name: broker
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    
  equipment:
    image: equipment
    build:
      context: .
      dockerfile: ./Dockerfile.equipment   
    volumes:
      - ./equipment/db/:/equipment/db
    depends_on:
      - broker 
    ports:
      - "6004:6004"

  monitor:
    image: monitor
    build:
      context: .
      dockerfile: ./Dockerfile.monitor
    depends_on:
      - broker


  bre:
    image: bre
    build:
      context: .
      dockerfile: ./Dockerfile.bre
    volumes:
      - ./bre/db/:/bre/db
    depends_on:
      - broker

  reporter:
    image: reporter
    build:
      context: .
      dockerfile: ./Dockerfile.reporter
    depends_on:
      - broker

  document:
    image: document
    build:
      context: .
      dockerfile: ./Dockerfile.document
    volumes:
      - ./document/db/:/document/db
    depends_on:
      - broker
    ports:
      - "6008:6008"

  mixer:
    image: mixer
    build:
      context: .
      dockerfile: ./Dockerfile.mixer
    depends_on:
      - broker

  connector:
    image: connector
    build:
      context: .
      dockerfile: ./Dockerfile.connector
    depends_on:
      - broker
    ports:
      - "6006:6006"


  crypto:
    image: crypto
    build:
      context: .
      dockerfile: ./Dockerfile.crypto
    depends_on:
      - broker

  storage:
    image: storage
    build:
      context: .
      dockerfile: ./Dockerfile.storage
    volumes:
      - ./storage/db/:/storage/db
    depends_on:
      - broker

